export { default as Footer } from "./Footer"
export { default as Navbar } from "./Navbar"
export { default as GameList } from "./gameComponent/GameList"
export { default as GameHistory } from "./gameComponent/GameHistory"
export { default as GameBox } from "./GameBox/Gamebox"
